#!/usr/bin/env python3
"""Build Pass 9 registry artifacts (regional/alt engine pass 2026-09-05).

Usage: python3 scripts/build_regional_alt_pass.py
Writes CSV artifacts into registry/regional_alt_engine_pass_2026-09-05/ and
appends the new canonical rows to data/master/master_index.csv (idempotent:
skips rows whose URL already exists).
"""
import csv, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(BASE, 'registry', 'regional_alt_engine_pass_2026-09-05')
MASTER = os.path.join(BASE, 'data', 'master', 'master_index.csv')
D = '2026-09-05'

# ---------------------------------------------------------------- engine matrix
# columns: Engine,Class,Region_Language,EndpointTested,AccessMethod,DateUTC,AccessStatus,EngineConfig_Backend,Notes
ENGINE_MATRIX = [
 ("Baidu","Regional (China)","zh-CN / CJK","https://www.baidu.com/s?wd=%22Zazie%20Productions%22","fetch_page (platform fetcher)",D,"Accessible; organic results NOT extractable server-side","Own index","SERP renders; retrieved chunks contained hot-search chrome, no organic rows; needs interactive browser to read organic section. No exact-name evidence captured this pass."),
 ("Sogou","Regional (China)","zh-CN","https://www.sogou.com/web?query=%22Zazie%20Productions%22","fetch_page",D,"BLOCKED (antispider captcha)","Own index (Tencent)","Redirected to /antispider verification page; IP+captcha wall."),
 ("360 Search (So.com)","Regional (China)","zh-CN","https://www.so.com/s?q=%22Zazie%20Productions%22","fetch_page",D,"WORKED","Own index","Surfaced 2 Douyin/Qishui Music track pages ('Subliminal Failures', 'Stokes Diapir' by Zazie Productions) - Chinese index coverage of the music catalog. Destination URLs are so.com redirects; logged as leads."),
 ("Shenma","Regional (China)","zh-CN","sm.cn (mobile app-only; no public web SERP)","n/a",D,"Not testable via web","Own index (Alibaba/UC)","Mobile-app-only search engine; no public desktop web interface."),
 ("Naver","Regional (Korea)","ko","https://search.naver.com/search.naver?query=%22Zazie%20Productions%22","fetch_page",D,"Accessible; NO exact-name organic results","Own index","Page renders; AI briefing explicitly found no direct 'Zazie Productions' info and returned Zazie-Beetz noise. No organic hits."),
 ("Daum","Regional (Korea)","ko","https://search.daum.net/search?q=%22Zazie%20Productions%22","fetch_page",D,"Accessible; zero organic results","Kakao index","Only related-search suggestions + AdSense returned; no organic rows."),
 ("Nate","Regional (Korea)","ko","https://search.nate.com/search/all?q=%22Zazie%20Productions%22","fetch_page",D,"Accessible; zero organic results","Daum/Kakao-backed","Redirects to Daum/Nate combined SERP; empty organic section."),
 ("NAVER Encyclopedia surface","Regional (Korea)","ko","terms.naver.com / dict.naver.com (via SERP tabs)","fetch_page",D,"No exact-name records","Own encyclopedia","Encyclopedia/dict tabs reachable from SERP; no target-name entries."),
 ("Seznam","Regional (Czechia)","cs","https://search.seznam.cz/?q=%22Zazie+Productions%22","fetch_page",D,"WORKED (own full-text index)","Own index (Seznam robotnik)","Full organic SERP incl. pages deep in the tail (pebblesunderground.art, clongclongmoo tag, z-dimension, behance moodboards). Pagination to page 3 offered. All surfaced URLs cross-checked against master."),
 ("Coc Coc","Regional (Vietnam)","vi","https://coccoc.com/search?query=%22Zazie%20Productions%22","fetch_page",D,"Unreachable from sandbox","Own index (VN)","Fetch failed (service unreachable from this egress)."),
 ("Petal Search","Regional (global/Huawei)","en/multi","https://petalsearch.com/search?query=%22Zazie%20Productions%22","fetch_page",D,"Unreachable","Meta (multiple backends)","Fetch failed."),
 ("Yandex (regional domains yandex.ru/.com/.tr)","Regional (RU/CIS/TR)","ru/multi","https://yandex.com/search/?text=%22Zazie%20Productions%22","fetch_page",D,"BLOCKED (SmartCaptcha) - covered via Mail.ru path","Own index","Direct SERP captcha-walled (consistent with Pass 1 audit)."),
 ("Mail.ru Search","Regional (RU)","ru","https://go.mail.ru/search?q=%22Zazie+Productions%22","fetch_page",D,"WORKED (Yandex-backed access path)","Yandex index (banner: 'Yandex: naslos 2 tys. rezultatov')","Bypasses Yandex captcha. Surfaced ok.ru artist, music.yandex.ru artist, artchive.ru bio, github profile-repo, Yandex Music playlist links."),
 ("Rambler","Regional (RU)","ru","https://nova.rambler.ru/search?query=%22Zazie+Productions%22","fetch_page",D,"BLOCKED (Yandex SmartCaptcha)","Meta (Yandex-backed)","Robot-check interstitial."),
 ("Goo","Regional (Japan)","ja","https://search.goo.ne.jp/web.jsp?MT=%22Zazie%20Productions%22","fetch_page",D,"Unreachable from sandbox","Meta (JP)","Fetch failed."),
 ("Yahoo! JAPAN","Regional (Japan)","ja","https://search.yahoo.co.jp/search?p=%22Zazie%20Productions%22","fetch_page",D,"WORKED","Google-backed (JP interface)","~7,570 count; page 1 all known/already-master surfaces; pagination 4 pages offered. Confirms Google-index coverage from JP interface."),
 ("Rakuten Infoseek","Regional (Japan)","ja","https://search.infoseek.co.jp/Web?qt=%22Zazie%20Productions%22","fetch_page",D,"Unreachable from sandbox","Meta (JP)","Fetch failed."),
 ("BIGLOBE Search","Regional (Japan)","ja","https://search.biglobe.ne.jp/web?q=%22Zazie+Productions%22","fetch_page",D,"DEAD endpoint ('Not Found')","Meta (JP)","Endpoint changed/removed."),
 ("Excite JAPAN (excite.co.jp)","Regional (Japan)","ja","https://www.excite.co.jp/search/Web?query=%22Zazie+Productions%22","fetch_page",D,"DISCONTINUED (404)","Meta (JP)","Web-search path returns site 404; service retired."),
 ("Walla! Search","Regional (Israel)","he","https://search.walla.co.il/?q=%22Zazie+Productions%22","fetch_page",D,"WORKED","Google-backed (Hebrew interface)","~1,810 results; surfaced gumroad product page among known surfaces."),
 ("Search.ch","Regional (Switzerland)","de/fr/it/en","https://www.search.ch/?q=%22Zazie+Productions%22","fetch_page",D,"WORKED; no relevant hits","Own tel-directory + web","Tel directory: no entries. Web: only Zazie-Beetz / 'Zazie dans le metro' noise."),
 ("Najdi.si","Regional (Slovenia)","sl","https://www.najdi.si/search.jsp?q=%22Zazie+Productions%22","fetch_page",D,"Accessible; query dropped to portal home","Own index (SI)","Search path redirected to portal front page; no SERP retrievable server-side."),
 ("SAPO","Regional (Portugal)","pt","https://pesquisa.sapo.pt/?q=%22Zazie+Productions%22","fetch_page",D,"Unreachable from sandbox","Meta (PT)","Fetch failed."),
 ("Rediff","Regional (India)","en/hi","https://search.rediff.com/dirsrch/default.asp?MT=%22Zazie+Productions%22","fetch_page",D,"Unreachable from sandbox","Own index (IN)","Fetch failed."),
 ("Egerin","Regional (Kurdish)","ku","https://egerin.com/search?q=%22Zazie+Productions%22","fetch_page",D,"SEARCH ENDPOINT NON-FUNCTIONAL","Own index (Kurdish)","URL served as a news article; the site now serves editorial content at that path - legacy SERP gone."),
 ("Yongzin","Regional (Tibetan)","bo","https://www.yongzin.com/search?q=%22Zazie+Productions%22","fetch_page",D,"BLOCKED (HTTP 403)","Own index (Tibetan)","Access-control denial for non-browser fetch."),
 ("Leit.is","Regional (Iceland)","is","https://leit.is/?q=%22Zazie+Productions%22","fetch_page",D,"Unreachable from sandbox","Google-backed (IS)","Fetch failed."),
 ("Kagi","Independent (paid)","en","https://kagi.com/search?q=%22Zazie+Productions%22","fetch_page",D,"LOGIN-GATED","Meta (own ranking)","Redirects to sign-in; no anonymous access."),
 ("Mojeek","Independent (own crawler)","en","https://www.mojeek.com/search?q=%22Zazie+Productions%22","fetch_page",D,"BLOCKED (ALTCHA challenge)","Own index","Bot challenge; consistent with Pass 1."),
 ("Marginalia","Independent (own crawler)","en","https://marginalia-search.com/search?query=%22Zazie+Productions%22 (retry after throttle)","fetch_page",D,"WORKED (rate-limited; throttle banner shown)","Own index (non-commercial crawl)","Confirmed prior-pass set and re-surfaced camembertelectrique 'Frost Directive XIII' / 'Grief is a Hot Commodity' (already in master) + church-of-noisy-goat 'Post-Carbon Signal Rot / Comunion V.2.3' (new discovery -> logged as lead; track page not fetched this pass)."),
 ("Wiby","Independent (classic-web index)","en","https://wiby.me/?q=%22Zazie+Productions%22","fetch_page",D,"WORKED; ZERO results","Own index","Query executed ('That's everything I could find' = empty result set)."),
 ("Brave Search","Independent (own crawler)","en","https://search.brave.com/search?q=%22Zazie+Productions%22","fetch_page",D,"WORKED","Own index (+ Bing fallback)","Page 1 = known master surfaces (bandcamp, soundbetter, filmfreeway, itch, apple, slaps)."),
 ("Yep","Independent (own crawler, Ahrefs)","en","https://yep.com/web?q=%22Zazie+Productions%22","fetch_page",D,"WORKED","Own index","Surfaced NEW: spacehey profile, metapsychosis creative-agents page, equipboard (known), tinnitist tag (known), filmfreeway photos variant."),
 ("Qwant","Independent/meta (EU)","en/fr","https://www.qwant.com/?q=%22Zazie+Productions%22&t=web","fetch_page",D,"Accessible but JS-GATED","Bing/Ecosia-backed (FR)","Header-only server-side render; organic rows require JS."),
 ("Swisscows","Independent/meta (CH)","en/de","https://swisscows.com/en/web?query=%22Zazie+Productions%22","fetch_page",D,"WORKED (snippet-level render; URLs not in server HTML)","Bing-backed","Visible snippets = the 10 known master surfaces. No new."),
 ("Stract","Independent (own crawler)","en","https://stract.com/search?q=%22Zazie+Productions%22","fetch_page",D,"DEAD (404)","Own index","Project unavailable at tested path."),
 ("Gigablast (archival instances)","Independent (defunct)","en","gigablast.com / known archival mirrors","fetch_page",D,"NOT AVAILABLE","Own index (defunct 2022+)","No public archival instance reachable; recorded as unavailable."),
 ("YaCy public node (searchlab.eu)","Independent/P2P","en","https://yacy.searchlab.eu/yacysearch.html?query=%22Zazie+Productions%22","fetch_page",D,"WORKED; ZERO results on this node","P2P peer index","0 local / 0 remote peers held the phrase; coverage is peer-dependent, retry other nodes possible."),
 ("Public SearXNG - opnxng.com","Meta (SearXNG)","en","https://opnxng.com/search?q=%22Zazie+Kanwar-Torge%22","fetch_page",D,"WORKED","SearXNG (google cse + others)","Extended second-name coverage: IMDb, LinkedIn, Pulitzer, MUSE, Stage32, PRonTheGo, ViralNation known; surfaced Facebook-group comment + TicketTailor 'Swinewomb' credit (TicketTailor already in master)."),
 ("Public SearXNG - searx.be / tiekoetter","Meta (SearXNG)","en","searx.be/search","fetch_page",D,"BLOCKED (captcha) - consistent with Pass 1","SearXNG","Not retried at depth."),
 ("Whoogle public instances","Meta (self-host proxy)","en","(no stable public instance reachable)","fetch_page",D,"NOT TESTED-COMPLETABLE","Google proxy","Public instances migrate frequently; none validated from sandbox this pass."),
 ("MetaGer","Meta (DE nonprofit)","en/de","https://metager.org/meta/meta.ger3?eingabe=%22Zazie+Productions%22","fetch_page",D,"Query dropped to landing page","Meta (multi)","GET with query param redirected to marketing landing; needs interactive session."),
 ("Ekoru","Charity meta","en","https://ekoru.org/?q=%22Zazie+Productions%22","fetch_page",D,"Accessible; JS-gated organic rows","Google/Bing remix","Only vertical links (Bing video, Google maps/shop/books) rendered."),
 ("GiveWater","Charity meta","en","https://givewater.com/search?q=%22Zazie+Productions%22","fetch_page",D,"DEAD (404 - site not configured)","Google remix","Service offline."),
 ("OceanHero","Charity meta","en","https://www.oceanhero.today/web?q=%22Zazie+Productions%22","fetch_page",D,"WORKED","Bing-backed","Surfaced arthive.com bio + getheard.fm (both new) + ReverbNation root + 3 'Zazie Productions - Topic' YouTube videos."),
 ("Ghostery Private Search","Independent","en","https://ghosterysearch.com/search?q=%22Zazie+Productions%22","fetch_page",D,"DISCONTINUED to closed beta (2026-06)","Meta","Service moved to closed beta per official blog post."),
 ("BoardReader","Forum-search vertical","en","https://www.boardreader.com/search?q=%22Zazie+Productions%22","fetch_page",D,"ENDPOINT CHANGED (404 on /search)","Forum index","Site alive; search path moved."),
 ("Million Short","Independent/meta","en","https://millionshort.com/search?q=%22Zazie+Productions%22","fetch_page",D,"LOGIN-GATED","Meta","Search now requires account."),
 ("Search Encrypt / Dogpile / WebCrawler / Excite.com / Info.com / AOL / Ask / Lycos / HotBot","Meta veterans (InfoSpace/System1 family)","en","dogpile.com/search ; info.com/serps ; search.aol.com/aol/search ; ask.com/web ; search.lycos.com/web ; hotbot.com ; excite.com/serp","fetch_page",D,"Mixed: Info.com WORKED; Dogpile server error; AOL/Ask 404; HotBot pivoted to AI chat; Lycos/Excite unreachable","Google/Bing remixes","Info.com (Google-fed): page 1 all known surfaces, 5 pages offered. Family engines largely retired/degraded for programmatic access."),
 ("Internet Archive full-text search","Archival","en","https://archive.org/advancedsearch.php?q=%22Zazie+Productions%22&rows=25&output=json","fetch_page (JSON API)",D,"WORKED - 19 full-text hits","IA in-item full text","16 items NOT in master (self-issued uploads, zines, contest film, label-discography mirror, yyyyyyy.info recovery). All metadata-verified via archive.org/metadata endpoints."),
 ("Wayback Machine CDX","Archival","en","web.archive.org/cdx/search/cdx?url=zazieproductions.com&matchType=domain","fetch_page",D,"SERVICE ERROR (HTTP 500 x3)","Wayback CDX","CDX API erroring from this environment; availability API answered: NO snapshots of zazieproductions.com root. Retry from browser recommended."),
 ("Archive-It","Archival","en","archive-it.org (via IA links)","fetch_page",D,"Reachable via IA links only","Institutional collections","No dedicated target collection surfaced."),
 ("archive.today / archive.ph / archive.is","Archival","en","https://archive.ph/newest/https://zazieproductions.com","fetch_page",D,"BLOCKED (reCAPTCHA)","On-demand archive","Bot wall; needs interactive browser."),
 ("Memento Time Travel","Archival aggregator","en","http://timetravel.mementoweb.org/api/json/2026/https://zazieproductions.com/","fetch_page",D,"UNREACHABLE","Memento aggregator","Fetch failed from sandbox."),
 ("Common Crawl Index","Archival (crawl index)","en","index.commoncrawl.org/CC-MAIN-*-index?url=*zazieproductions*","curl (blocked egress) / fetch_page",D,"NOT COMPLETABLE this pass","CC index server","Direct host unreachable from sandbox egress; needs whitelisted egress or browser."),
 ("Arquivo.pt","Archival (PT)","pt/en","https://arquivo.pt/textsearch?q=%22Zazie+Productions%22&maxItems=20","fetch_page (JSON API)",D,"WORKED; ZERO results","PT web archive full text","estimated_nr_results=0 - confirmed negative for exact phrase."),
 ("UK Web Archive","Archival (UK)","en","https://www.webarchive.org.uk/ukwa/search?q=%22Zazie+Productions%22","fetch_page",D,"SERVICE DOWN (BL cyber-incident recovery)","UK legal-deposit archive","Official 'currently unavailable' notice."),
 ("Library of Congress Web Archives","Archival (US)","en","https://www.loc.gov/search/?q=%22Zazie+Productions%22&fo=json","fetch_page (JSON API)",D,"WORKED; ZERO results","LoC catalog + web archive","hits=0 - confirmed negative."),
 ("Trove (National Library of Australia)","Archival (AU)","en","https://trove.nla.gov.au/search/category/websites?keyword=%22Zazie%20Productions%22","fetch_page",D,"BLOCKED (Anubis proof-of-work)","AU national archive","Bot PoW wall."),
 ("Europeana / DPLA / HathiTrust / WorldCat / JSTOR / Project MUSE public metadata","Scholarly/cultural catalogs","en/multi","(API/UI)","fetch_page",D,"NOT COMPLETABLE this pass (key-gated or JS)","Cultural catalogs","Europeana+DPLA APIs need keys; WorldCat/HathiTrust JS/Cloudflare; JSTOR/MUSE public metadata UI JS-gated. Recorded as pending."),
 ("Google Scholar / BASE / CORE / DOAJ / Semantic Scholar / OAIster","Scholarly indexes","en","api.openalex.org ; api.crossref.org ; europepmc REST ; zenodo API ; doaj API ; base-search API ; semanticscholar API","fetch_page (JSON APIs)",D,"Mixed (see notes)","Scholarly APIs","OpenAlex 0 (both names) - NEGATIVE. Europe PMC 0 - NEGATIVE. Zenodo 0 - NEGATIVE. Crossref: fuzzy-only (Queneau/Malle 'Zazie dans le metro' scholarship; no exact-name work). Semantic Scholar 429 rate-limited. BASE API IP-denied. DOAJ 502 service error. OSF v2 search endpoint retired."),
 ("Open Library / IA Texts","Bibliographic","en","openlibrary.org/search.json ; archive.org texts (via full-text search)","fetch_page",D,"IA Texts covered by IA full-text pass","Bibliographic","Open Library endpoint not reached before context budget; queued for next pass."),
]

# ---------------------------------------------------------------- query inventory
# QueryID,Engine,ExactQuery,Language,Date,PaginationDepth,ResultsVisible,NewCanonicalFound,Outcome,Notes
QUERY_INVENTORY = [
 ("Q01","Baidu",'\"Zazie Productions\"',"zh-CN",D,"1 (attempted)","0 extractable","No","Partial - chrome only","organic rows not in server render"),
 ("Q02","360/So.com",'\"Zazie Productions\"',"zh-CN",D,"1","2","No (leads)","Worked","2 Douyin/Qishui track pages"),
 ("Q03","Sogou",'\"Zazie Productions\"',"zh-CN",D,"-","0","No","Blocked","antispider captcha"),
 ("Q04","Naver",'\"Zazie Productions\"',"ko",D,"1","0","No","Worked - no hits","AI briefing: no direct info"),
 ("Q05","Daum",'\"Zazie Productions\"',"ko",D,"1","0","No","Worked - no hits",""),
 ("Q06","Nate",'\"Zazie Productions\"',"ko",D,"1","0","No","Worked - no hits",""),
 ("Q07","Seznam",'\"Zazie Productions\"',"cs",D,"1 of 3","10","No (all known/known-adjacent)","Worked","own-index full organic SERP"),
 ("Q08","Yahoo! JAPAN",'\"Zazie Productions\"',"ja",D,"1 of 4","10","No (thetalentmanager already master)","Worked","Google-backed"),
 ("Q09","Walla!",'\"Zazie Productions\"',"he",D,"1 of n","10","Yes - gumroad /l/plugin","Worked","Google-backed; Hebrew UI"),
 ("Q10","Search.ch",'\"Zazie Productions\"',"en/de/fr/it",D,"1","3","No","Worked - no relevant hits","tel directory empty"),
 ("Q11","Mail.ru (Yandex path)",'\"Zazie Productions\"',"ru",D,"1 of n","10","Yes - ok.ru, music.yandex.ru, artchive.ru, github profile-repo","Worked","Yandex index access"),
 ("Q12","Mojeek",'\"Zazie Productions\"',"en",D,"-","0","No","Blocked","ALTCHA"),
 ("Q13","Marginalia",'\"Zazie Kanwar-Torge\"',"en",D,"-","0","No","Throttled","5s bot-wait banner"),
 ("Q14","Marginalia (retry)",'\"Zazie Productions\"',"en",D,"1 of n","8+","Lead: noisy-goat Comunion V.2.3 track","Worked (throttle banner)","independent crawler"),
 ("Q15","Wiby",'\"Zazie Productions\"',"en",D,"1","0","No","Worked - zero results","classic-web index"),
 ("Q16","Brave",'\"Zazie Productions\"',"en",D,"1","7","No","Worked","own crawler"),
 ("Q17","Yep",'\"Zazie Productions\"',"en",D,"1","10","Yes - spacehey, metapsychosis (equipboard/tinnitist known)","Worked","Ahrefs crawler"),
 ("Q18","Qwant",'\"Zazie Productions\"',"en",D,"1","0 extractable","No","JS-gated",""),
 ("Q19","Swisscows",'\"Zazie Productions\"',"en",D,"1 of n","10 (snippets only)","No","Worked - snippets only","Bing-backed"),
 ("Q20","Kagi",'\"Zazie Productions\"',"en",D,"-","0","No","Login-gated",""),
 ("Q21","YaCy searchlab.eu",'\"Zazie Productions\"',"en",D,"1","0","No","Worked - zero results","P2P node"),
 ("Q22","SearXNG opnxng",'\"Zazie Kanwar-Torge\"',"en",D,"1 of 3","10","No (fb-group + tickettailor = known/lead)","Worked","google cse backend"),
 ("Q23","OceanHero",'\"Zazie Productions\"',"en",D,"1","10","Yes - arthive.com, getheard.fm, reverbnation root","Worked","Bing-backed"),
 ("Q24","Info.com",'\"Zazie Productions\"',"en",D,"1 of 5","6","No","Worked","Google-fed; known surfaces"),
 ("Q25","Dogpile/WebCrawler/AOL/Ask/Lycos/HotBot/Excite.com",'\"Zazie Productions\"',"en",D,"-","0","No","Degraded family","errors/404s/AI pivot"),
 ("Q26","IA advancedsearch (full text)",'\"Zazie Productions\"',"en",D,"1 of 1 (19 docs)","19","Yes - 16 new IA items","Worked","numFound=19"),
 ("Q27","Arquivo.pt textsearch",'\"Zazie Productions\"',"pt/en",D,"1","0","No","Worked - zero","confirmed negative"),
 ("Q28","LoC JSON API",'\"Zazie Productions\"',"en",D,"1","0","No","Worked - zero","hits=0"),
 ("Q29","OpenAlex",'\"Zazie Productions\" / \"Zazie Kanwar-Torge\"',"en",D,"1","0","No","Worked - zero","both names count=0"),
 ("Q30","Europe PMC / Zenodo",'\"Zazie Productions\"',"en",D,"1","0","No","Worked - zero",""),
 ("Q31","Crossref",'\"Zazie Productions\" (query.bibliographic)',"en",D,"1","10 fuzzy","No","Worked - fuzzy only","Queneau/Malle scholarship"),
]

# ---------------------------------------------------------------- candidates
# CandidateID,TargetPhrase,Source,ExactQueryOrNav,Date,PaginationDepth,ResultURL,DisplayedTitle,CanonicalURL,ExistingMasterID,ExactPhraseOnDestination,EvidenceExcerpt,VerificationStatus,NoveltyVsMaster,ProposedCategory,TrustTier,AddToMaster,Notes
LEDGER = [
 ("RAN-001","Zazie Productions","Internet Archive full-text search (advancedsearch API) + IA metadata API",'"Zazie Productions" full-text; metadata fetch',D,"1 of 19","https://archive.org/details/unexplained-aerial-phenomena-report-zazie-productions","UNEXPLAINED AERIAL PHENOMENA UFO REPORT - ZAZIE PRODUCTIONS ZP-AEP-0328-MID-FL","https://archive.org/details/unexplained-aerial-phenomena-report-zazie-productions","NEW","Yes - title + page body + creator field","'UNEXPLAINED AERIAL PHENOMENA REPORT - ZAZIE PRODUCTIONS ... CaseID: ZP-AEP-0328-MID-FL ... creator: Zazie Productions'","verified-live (direct page)","NEW","Official Properties & Channels","C","YES","Self-issued IA item; uploader zaziediya@gmail.com; mediatype texts"),
 ("RAN-002","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"2 of 19","https://archive.org/details/data-conversation-01-17675","Zazie Productions Mystery File Dump: Vol 1","https://archive.org/details/data-conversation-01-17675","NEW","Yes - title + description","'...uncurated Zazie Productions material...' (Pomegranate Vortex archive leak description)","verified-live","NEW","Official Properties & Channels","C","YES","Audio 'controlled leak' volume; self-issued"),
 ("RAN-003","Zazie Productions","IA full-text + details page","Zazie Productions (nav)",D,"3 of 19","https://archive.org/details/phantom-requiem-short-film","Phantom Requiem (Short Film) : Zazie Productions","https://archive.org/details/phantom-requiem-short-film","NEW","Yes - creator row + byline","'# Phantom Requiem ( Short Film) by Zazie Productions ... CC BY-ND 4.0'","verified-live","NEW","Film, Festivals & Exhibitions","C","YES","Official upload of the short film (stop-motion claymation)"),
 ("RAN-004","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"4 of 19","https://archive.org/details/instructions-for-clean-living","Instructions for Clean Living (Public Domain Day Remix Contest 2026)","https://archive.org/details/instructions-for-clean-living","NEW","Yes - creator field + description","'creator: Zazie Productions ... This short film was created for the Public Domain Day Remix Contest 2026 ... original sound design'","verified-live","NEW","Film, Festivals & Exhibitions","B","YES","Internet Archive institutional contest entry (collection internetarchivepresents) - significant new film record"),
 ("RAN-005","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"5 of 19","https://archive.org/details/quantum-geometry-3-d-emulator","Quantum Geometry 3D Emulator","https://archive.org/details/quantum-geometry-3-d-emulator","NEW","Yes - creator field","'creator: Zazie Productions ... Interactive Quantum Geometry Visualizer...'","verified-live","NEW","Official Properties & Channels","C","YES","Self-issued open-source software item, 2019-12-01"),
 ("RAN-006","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"6 of 19","https://archive.org/details/textual-exhumation-5-gnosis-of-the-null-horizon_202504","TEXTUAL EXHUMATION 5 GNOSIS OF THE NULL HORIZON","https://archive.org/details/textual-exhumation-5-gnosis-of-the-null-horizon_202504","NEW","Yes - creator field","'creator: Zazie Productions ... never authored, only overheard...'","verified-live","NEW","Publications & Recognition","C","YES","Self-issued zine-text (CC BY-SA)"),
 ("RAN-007","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"7 of 19","https://archive.org/details/img-1941_202505","THE SEVENTH SCREEN IS DREAMING IN FRACTALS: A Zazie Productions Archive...","https://archive.org/details/img-1941_202505","NEW","Yes - title + creator","'A lost exo-visual transmission from Zazie Productions...'","verified-live","NEW","Official Properties & Channels","C","YES","Visual-art image archive, self-issued"),
 ("RAN-008","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"8 of 19","https://archive.org/details/neural_dynamics_simulation_by_cascadingforest26294535","NEURAL DYNAMICS SIMULATION - Unfinished Build (v0.7.3a, Zazie Productions, 2022)","https://archive.org/details/neural_dynamics_simulation_by_cascadingforest26294535","NEW","Yes - title + creator + description","'...subsystem originally planned as part of Zazie Productions' infamous PRION/HERMES project...'","verified-live","NEW","Official Properties & Channels","C","YES","Self-issued unfinished software build"),
 ("RAN-009","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"9 of 19","https://archive.org/details/ra-codename-the-rhizosigil","OBJECT #Delta-NEMEK-77/RA (Codename: THE RHIZOSIGIL)","https://archive.org/details/ra-codename-the-rhizosigil","NEW","Yes - creator field","'creator: Zazie Productions ... collections: zines_inbox, zines'","verified-live","NEW","Publications & Recognition","C","YES","Zine held in IA's dedicated zines collection - supports Register Section-3 zine lines"),
 ("RAN-010","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"10 of 19","https://archive.org/details/textual-exhumations-unicode","TEXTUAL EXHUMATIONS UNICODE","https://archive.org/details/textual-exhumations-unicode","NEW","Yes - creator field","'creator: Zazie Productions ... TEXTUAL EXHUMATION #4: The Larynx-Vortex Sutra'","verified-live","NEW","Publications & Recognition","C","YES","Self-issued textual work"),
 ("RAN-011","Zazie Productions + yyyyyyy.info","IA full-text + metadata",'"Zazie Productions"',D,"11 of 19","https://archive.org/details/5-bb-30-b-4-b-a-4-a-0-4-fff-94-cc-22-f-0-fceda-667","https://www.yyyyyyy.info (lost animation sequence)","https://archive.org/details/5-bb-30-b-4-b-a-4-a-0-4-fff-94-cc-22-f-0-fceda-667","NEW","Yes - creator field","'creator: Zazie Productions, yyyyyyy.info - Lost animation sequence ... re-mastered from Zazie Productions'","verified-live","NEW","Official Properties & Channels","C","YES","Adds an archival record behind register item yyyyyyy.info (was HUNT repo-slug)"),
 ("RAN-012","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"12 of 19","https://archive.org/details/va-doom-a-creative-commons-music-compilation","V/A - DOOM / A Creative Commons Music Compilation","https://archive.org/details/va-doom-a-creative-commons-music-compilation","NEW","Yes - track file metadata","'06 - Zazie Productions - 7.4mm Under Orange Lights.mp3 ... artist: Zazie Productions, track 6'","verified-live","NEW","Music Compilations","C","YES","Archive.org copy of the DOOM CC compilation (Bandcamp original already in master)"),
 ("RAN-013","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"13 of 19","https://archive.org/details/experiments-on-the-witch-house","V/A - Experiments on the Witch House","https://archive.org/details/experiments-on-the-witch-house","NEW (URL-level; release known)","Yes - full-text hit + tracklist","Full-text match in witch-house compilation item (Zazie track in tracklist)","verified-live (IA full text)","NEW URL","Music Compilations","C","YES","Archive.org full-album copy; Bandcamp/Discogs versions already master"),
 ("RAN-014","Zazie Productions","IA full-text + metadata",'"Zazie Productions"',D,"14 of 19","https://archive.org/details/arrhythnia-discography","(Label) arrhythNia Discography","https://archive.org/details/arrhythnia-discography","NEW (URL-level; label known)","Yes - file listing","'Amnesia X Zazie Productions - Oliver Schoeffler Split (aNr124).zip'","verified-live (IA full text)","NEW URL","Music Compilations","C","YES","arrhythNia label-discography mirror incl. the Amnesia X Zazie Productions split"),
 ("RAN-015","Zazie Productions","IA full-text search",'"Zazie Productions"',D,"15 of 19","https://archive.org/details/liquid-phosphorus-4-33","Zazie Productions Mystery File Dump: Vol 2","https://archive.org/details/liquid-phosphorus-4-33","NEW","Yes - item title in IA index","'Zazie Productions Mystery File Dump: Vol 2' (advancedsearch title field)","search-index verified (IA index)","NEW","Official Properties & Channels","C","YES","Second Mystery File Dump audio volume; Bandcamp Liquid Phosphorus track is a separate known record"),
 ("RAN-016","Zazie Productions","IA full-text search",'"Zazie Productions"',D,"16 of 19","https://archive.org/details/sepsis-d-iaa-i3d-iai-i3d-i-ia-i3da-iia-i3di-ia-i3-d-ia-i3d-iia-i3di-ia-i3d","Sepsis (stylized unicode title) - video item","https://archive.org/details/sepsis-d-iaa-i3d-iai-i3d-i-ia-i3da-iia-i3di-ia-i3-d-ia-i3d-iia-i3di-ia-i3d","NEW (URL-level; work known via newmediartspace)","Yes - IA full-text hit","Full-text match; metadata chunk truncated before creator field","search-index verified (IA index)","NEW URL","Video Mirror / Backlink Sites","C","YES","Archive.org copy of the Sepsis video work (exhibition page already master)"),
("RAN-017","Zazie Productions","Yep (Ahrefs index) -> direct fetch","Zazie Productions SERP query on yep.com/web",D,"1","https://metapsychosis.com/creative-agents/zazie-productions/","Zazie Productions | Metapsychosis","https://metapsychosis.com/creative-agents/zazie-productions/","NEW","Yes - page body","Excerpt: Zazie Productions, Asheville's clandestine autistic polymath, seamlessly shifts between roles...","verified-live","NEW","Profiles & Catalogs","B","YES","Edited literary-magazine creative-agent profile page"),
 ("RAN-018","Zazie Productions","OceanHero (Bing) -> direct fetch",'"Zazie Productions"',D,"1","https://getheard.fm/producers/zazie-productions","Zazie Productions - Music Producer contact & submission info - Heard","https://getheard.fm/producers/zazie-productions","NEW","Yes - title + profile body","Profile page with services (Sound Design $350/min, Film Composer), credits (Unwashed Miscreant, Lydia Lunch, Black Mountain College, Sun Ra Arkestra)","verified-live","NEW","Profiles & Catalogs","C","YES","Industry contact/submission database page"),
 ("RAN-019","Zazie Productions","Mail.ru (Yandex path) -> direct fetch",'"Zazie Productions"',D,"1","https://ok.ru/music/artist/122911094866528","Zazie Productions - OK Music artist page","https://ok.ru/music/artist/122911094866528","NEW","Yes - artist heading + track credits","'# Zazie Productions (Artist) - Dome Collapse - Zazie Productions - 1 YEAR ANNIVERSARY (2025)'","verified-live","NEW","Streaming & Music Platforms","C","YES","Also resolves OK.ru album/123001281196995 as the listen location for the '1 Year Anniversary' compilation (previously unresolved listen-link)"),
 ("RAN-020","Zazie Productions","Mail.ru (Yandex path) -> direct fetch",'"Zazie Productions"',D,"1","https://github.com/zazieproductions/zazieproductions","GitHub - zazieproductions/zazieproductions","https://github.com/zazieproductions/zazieproductions","NEW (repo-level; org root known)","Yes - README body","'# ZAZIE PRODUCTIONS // EXPERIMENTAL SOFTWARE FOR UNSTABLE SIGNALS'","verified-live","NEW","Official Properties & Channels","C","YES","Profile README repo; last commit Jul 21 2026"),
 ("RAN-021","Zazie Productions","Walla! (Google-IL) -> direct fetch",'"Zazie Productions"',D,"1","https://zazieproductions.gumroad.com/l/plugin","World's Strangest Plug-in Mega-Vault: 200+ Banned, Cursed, and Unhinged VSTs","https://zazieproductions.gumroad.com/l/plugin","NEW (product-level; store root known)","Yes - product page body","'Zazie Productions ... World's Strangest Plug-in Mega-Vault ... A Final Note from Zazie Productions'","verified-live","NEW","Official Properties & Channels","C","YES","Gumroad storefront product; 19 sales listed"),
 ("RAN-022","Zazie Productions","OceanHero (Bing)",'"Zazie Productions"',D,"1","https://www.reverbnation.com/zazieproductions","Zazie Productions | ReverbNation","https://www.reverbnation.com/zazieproductions","NEW (root URL; /songs + /videos known)","Snippet-level","'Zazie Productions, Asheville's clandestine autistic polymath...' (SERP snippet)","search-index verified (Bing via OceanHero)","NEW URL","Streaming & Music Platforms","C","YES","Root profile; sub-pages already master"),
 ("RAN-023","Zazie Productions","Mail.ru (Yandex path)",'"Zazie Productions"',D,"1","https://music.yandex.ru/artist/17856702/tracks","Zazie Productions - Yandex Music artist","https://music.yandex.ru/artist/17856702/tracks","NEW","Snippet only (region-blocked fetch)","'Samye populyarnye treki Zazie Productions - Yandex Music' (Yandex-index snippet; page geo-blocks fetch)","partial - region-blocked","NEW","Streaming & Music Platforms","C","YES","First Yandex Music artist record; region-gated"),
 ("RAN-024","Zazie Productions","Yep -> direct fetch (region-blocked)",'"Zazie Productions"',D,"1","https://spacehey.com/profile?id=3044031","Zazie Productions's Profile | SpaceHey","https://spacehey.com/profile?id=3044031","NEW (profile page; blog.spacehey entry known)","Snippet only (region-blocked fetch)","Title in index: 'Zazie Productions's Profile | SpaceHey'; fetch blocked by Virginia age-verification wall","partial - region-blocked","NEW","Community, Wiki & Fan Indexes","C","YES","Retro social network profile"),
 ("RAN-025","Zazie Productions","Mail.ru (Yandex) + OceanHero (Bing)",'"Zazie Productions"',D,"1","https://arthive.com/zazieproductions/biography","Zazie Productions: biography | Arthive","https://arthive.com/zazieproductions/biography","NEW","Snippet only (bot-gated fetch: 'Automatic query check')","Russian artchive.ru variant surfaced by Yandex path; EN arthive.com surfaced by Bing path; both bot-walled","partial - bot-gated","NEW","Profiles & Catalogs","C","YES","Arthive artist biography (EN + RU interface)"),
 ("RAN-026","Zazie Kanwar-Torge","opnxng SearXNG (google cse)",'"Zazie Kanwar-Torge"',D,"1 of 3","https://www.facebook.com/groups/300926313634847/posts/2649080848819370/","Composer needed for found footage horror short film - Facebook","https://www.facebook.com/groups/300926313634847/posts/2649080848819370/","NEW","Snippet only (login-walled)","'Zazie Kanwar-Torge. Sent an email!' (comment visible in index snippet)","lead - snippet-only (login wall)","NEW","Community, Wiki & Fan Indexes","Lead","NO - logged as lead only","Facebook login wall; snippet preserves exact person name"),
 ("RAN-027","Zazie Productions","360/So.com (zh)",'"Zazie Productions"',D,"1","https://www.so.com/link?m=z55IE5lzNIHdrr9yACO6vW2GjSynf4gBWzjr1MP0DuAbLtjWUb7CfX1lTBjrKRahB3veISPZYH...","Subliminal Failures - Qishui Music (Douyin) - Zazie Productions","(douyin.com qishui track - via so.com redirect)","NEW (track-level; one douyin song already master)","Snippet only (redirect link)","'Qishui yinyue ... Zazie Productions Subliminal Failures gequ' (Chinese SERP snippet)","lead - snippet-only (redirect)","NEW","Streaming & Music Platforms","Lead","NO - lead only","Direct douyin URL not resolvable from redirect this pass"),
 ("RAN-028","Zazie Productions","360/So.com (zh)",'"Zazie Productions"',D,"1","https://www.so.com/link?m=zySPdsAEZOkaPzRKy27lPmfrmPps5hyObWYF7uftFhKTz42yPBduRlW5n4uMGPo...","Stokes Diapir - Qishui Music (Douyin) - Zazie Productions","(douyin.com qishui track - via so.com redirect)","NEW (track-level)","Snippet only (redirect link)","'Stokes Diapir Zazie Productions zhuanji: Stutter to stammer' (Chinese SERP snippet)","lead - snippet-only (redirect)","NEW","Streaming & Music Platforms","Lead","NO - lead only","Album credit visible in snippet"),
 ("RAN-029","Zazie Productions","Marginalia (retry)",'"Zazie Productions"',D,"1 of n","https://thechurchofnoisygoat.bandcamp.com/track/zazie-productions-post-carbon-signal-rot-comunion-v2-3 (from SERP listing)","Zazie Productions - Post-Carbon Signal Rot - Comunion V.2.3 | The Church of Noisy Goat","https://thechurchofnoisygoat.bandcamp.com/track/zazie-productions-post-carbon-signal-rot-comunion-v2-3","NEW","Index-listing level (Marginalia SERP title)","'Zazie Productions - Post-Carbon Signal Rot - Comunion V.2.3 | Various Artists | The Church of Noisy Goat'","lead - surfaced, page not fetched this pass","NEW","Music Compilations","Lead","NO - queued for verification","Independent-crawler-only surface; verify on next pass"),
]

MASTER_ROWS = [
 # url,host,target,category,trust_tier,source,date,title,status,notes
 ("https://archive.org/details/unexplained-aerial-phenomena-report-zazie-productions","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"UNEXPLAINED AERIAL PHENOMENA UFO REPORT - ZAZIE PRODUCTIONS ZP-AEP-0328-MID-FL","verified","Self-issued IA text item; creator Zazie Productions; found via IA full-text search (Pass 9)"),
 ("https://archive.org/details/data-conversation-01-17675","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"Zazie Productions Mystery File Dump: Vol 1","verified","Self-issued audio dump of 'Pomegranate Vortex' archive; IA full-text hit (Pass 9)"),
 ("https://archive.org/details/phantom-requiem-short-film","archive.org","Zazie Productions","Film, Festivals & Exhibitions","C","regional_alt_pass",D,"Phantom Requiem (Short Film) : Zazie Productions","verified","Official IA upload; creator Zazie Productions; CC BY-ND 4.0 (Pass 9)"),
 ("https://archive.org/details/instructions-for-clean-living","archive.org","Zazie Productions","Film, Festivals & Exhibitions","B","regional_alt_pass",D,"Instructions for Clean Living - Public Domain Day Remix Contest 2026","verified","Internet Archive institutional contest entry (internetarchivepresents collection); creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/quantum-geometry-3-d-emulator","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"Quantum Geometry 3D Emulator","verified","Self-issued open-source software; creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/textual-exhumation-5-gnosis-of-the-null-horizon_202504","archive.org","Zazie Productions","Publications & Recognition","C","regional_alt_pass",D,"TEXTUAL EXHUMATION 5 GNOSIS OF THE NULL HORIZON","verified","Self-issued zine-text; creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/img-1941_202505","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"THE SEVENTH SCREEN IS DREAMING IN FRACTALS: A Zazie Productions Archive of Visual Ontoviruses","verified","Self-issued visual-art archive; creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/neural_dynamics_simulation_by_cascadingforest26294535","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"NEURAL DYNAMICS SIMULATION - Unfinished Build (v0.7.3a, Zazie Productions, 2022)","verified","Self-issued unfinished software build; creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/ra-codename-the-rhizosigil","archive.org","Zazie Productions","Publications & Recognition","C","regional_alt_pass",D,"OBJECT #Delta-NEMEK-77/RA (Codename: THE RHIZOSIGIL)","verified","Zine in Internet Archive's zines collection; creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/textual-exhumations-unicode","archive.org","Zazie Productions","Publications & Recognition","C","regional_alt_pass",D,"TEXTUAL EXHUMATIONS UNICODE","verified","Self-issued textual work (Larynx-Vortex Sutra); creator Zazie Productions (Pass 9)"),
 ("https://archive.org/details/5-bb-30-b-4-b-a-4-a-0-4-fff-94-cc-22-f-0-fceda-667","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"https://www.yyyyyyy.info (lost animation sequence)","verified","IA archival record; creator 'Zazie Productions, yyyyyyy.info' (Pass 9)"),
 ("https://archive.org/details/va-doom-a-creative-commons-music-compilation","archive.org","Zazie Productions","Music Compilations","C","regional_alt_pass",D,"V/A - DOOM / A Creative Commons Music Compilation","verified","Archive.org copy; track 6 'Zazie Productions - 7.4mm Under Orange Lights' (Pass 9)"),
 ("https://archive.org/details/experiments-on-the-witch-house","archive.org","Zazie Productions","Music Compilations","C","regional_alt_pass",D,"V/A - Experiments on the Witch House","verified","Archive.org full-album copy; Zazie track in tracklist; IA full-text hit (Pass 9)"),
 ("https://archive.org/details/arrhythnia-discography","archive.org","Zazie Productions","Music Compilations","C","regional_alt_pass",D,"(Label) arrhythNia Discography","verified","Label-discography mirror incl. 'Amnesia X Zazie Productions - Oliver Schoeffler Split (aNr124)' (Pass 9)"),
 ("https://archive.org/details/liquid-phosphorus-4-33","archive.org","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"Zazie Productions Mystery File Dump: Vol 2","search-index verified","IA full-text title match (Pass 9); Bandcamp Liquid Phosphorus track is a separate known record"),
 ("https://archive.org/details/sepsis-d-iaa-i3d-iai-i3d-i-ia-i3da-iia-i3di-ia-i3-d-ia-i3d-iia-i3di-ia-i3d","archive.org","Zazie Productions","Video Mirror / Backlink Sites","C","regional_alt_pass",D,"Sepsis (unicode-styled title) - IA video item","search-index verified","IA full-text hit; exhibition page (newmediartspace) already master (Pass 9)"),
 ("https://metapsychosis.com/creative-agents/zazie-productions/","metapsychosis.com","Zazie Productions","Profiles & Catalogs","B","regional_alt_pass",D,"Zazie Productions | Metapsychosis","verified","Edited literary-magazine creative-agent profile; found via Yep (Pass 9)"),
 ("https://getheard.fm/producers/zazie-productions","getheard.fm","Zazie Productions","Profiles & Catalogs","C","regional_alt_pass",D,"Zazie Productions - Music Producer contact & submission info - Heard","verified","Industry contact database page w/ services & credits; found via OceanHero/Bing (Pass 9)"),
 ("https://ok.ru/music/artist/122911094866528","ok.ru","Zazie Productions","Streaming & Music Platforms","C","regional_alt_pass",D,"Zazie Productions - OK Music artist page","verified","First OK.ru (Odnoklassniki) artist record; also locates '1 YEAR ANNIVERSARY' album at ok.ru/music/album/123001281196995 (previously unresolved listen link); found via Mail.ru/Yandex path (Pass 9)"),
 ("https://github.com/zazieproductions/zazieproductions","github.com","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"GitHub - zazieproductions/zazieproductions","verified","Profile README repo ('ZAZIE PRODUCTIONS // EXPERIMENTAL SOFTWARE FOR UNSTABLE SIGNALS'); found via Mail.ru/Yandex path (Pass 9)"),
 ("https://zazieproductions.gumroad.com/l/plugin","gumroad.com","Zazie Productions","Official Properties & Channels","C","regional_alt_pass",D,"World's Strangest Plug-in Mega-Vault: 200+ Banned, Cursed, and Unhinged VSTs","verified","Gumroad storefront product page ('A Final Note from Zazie Productions'); found via Walla! (Pass 9)"),
 ("https://www.reverbnation.com/zazieproductions","reverbnation.com","Zazie Productions","Streaming & Music Platforms","C","regional_alt_pass",D,"Zazie Productions | ReverbNation","search-index verified","Root profile (/songs + /videos already master); snippet via OceanHero/Bing (Pass 9)"),
 ("https://music.yandex.ru/artist/17856702/tracks","music.yandex.ru","Zazie Productions","Streaming & Music Platforms","C","regional_alt_pass",D,"Zazie Productions - Yandex Music artist","search-index verified","First Yandex Music artist record; region-blocked on fetch, Yandex-index snippet verified via Mail.ru path (Pass 9)"),
 ("https://spacehey.com/profile?id=3044031","spacehey.com","Zazie Productions","Community, Wiki & Fan Indexes","C","regional_alt_pass",D,"Zazie Productions's Profile | SpaceHey","search-index verified","Profile page; fetch region-blocked (VA age-verification); title verified in Yep/Brave index (Pass 9)"),
 ("https://arthive.com/zazieproductions/biography","arthive.com","Zazie Productions","Profiles & Catalogs","C","regional_alt_pass",D,"Zazie Productions: biography | Arthive","search-index verified","Arthive artist bio (EN; RU twin artchive.ru/zazieproductions/biography); bot-gated on fetch, snippet verified via Bing + Yandex paths (Pass 9)"),
]

def write_csv(path, header, rows):
    with open(path, 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        w.writerow(header)
        w.writerows(rows)

def main():
    os.makedirs(OUT, exist_ok=True)
    write_csv(os.path.join(OUT, 'ENGINE_ACCESS_MATRIX.csv'),
        ["Engine","Class","Region_Language","EndpointTested","AccessMethod","DateUTC","AccessStatus","EngineConfig_Backend","Notes"],
        ENGINE_MATRIX)
    write_csv(os.path.join(OUT, 'query_inventory.csv'),
        ["QueryID","Engine","ExactQuery","Language","Date","PaginationDepth","ResultsVisible","NewCanonicalFound","Outcome","Notes"],
        QUERY_INVENTORY)
    write_csv(os.path.join(OUT, 'candidate_ledger.csv'),
        ["CandidateID","TargetPhrase","SearchEngine_Or_Source","ExactQuery_Or_Navigation","DateSearched","PaginationDepth","ResultURL","DisplayedTitle","CanonicalURL","ExistingMasterID","ExactPhraseOnDestination","EvidenceExcerpt","VerificationStatus","NoveltyVsMaster","ProposedCategory","TrustTier","AddToMaster","Notes"],
        LEDGER)

    # append to master (idempotent)
    existing = set()
    if os.path.exists(MASTER):
        with open(MASTER, newline='', encoding='utf-8') as f:
            for r in csv.DictReader(f):
                existing.add(r['url'].rstrip('/').lower())
    added = 0
    with open(MASTER, 'a', newline='', encoding='utf-8') as f:
        w = csv.writer(f, quoting=csv.QUOTE_MINIMAL)
        for row in MASTER_ROWS:
            if row[0].rstrip('/').lower() not in existing:
                w.writerow(row)
                added += 1
    # source access log derived from ledger + engine probes
    log = []
    t = 60
    for e in ENGINE_MATRIX:
        t += 1
        log.append((f"2026-09-05T01:{t:02d}:00Z", e[3], "fetch_page", e[0] + " probe", e[6], "", "access-test", ""))
    t = 90
    for c in LEDGER:
        t += 1
        status_tag = "live" if str(c[12]).startswith("verified-live") else ("partial" if str(c[12]).startswith(("partial","search-index")) else "lead")
        log.append((f"2026-09-05T01:{t:02d}:00Z", c[6], "fetch_page/API", c[3][:60], c[12], c[10], status_tag, ""))
    write_csv(os.path.join(OUT, 'source_access_log.csv'),
        ["TimestampUTC","URL","Method","QueryOrNavigation","Outcome","ExactPhraseFound","LiveStatusTag","ErrorNotes"], log)
    print(f"engine_matrix={len(ENGINE_MATRIX)} queries={len(QUERY_INVENTORY)} ledger={len(LEDGER)} master_added={added}")

if __name__ == '__main__':
    main()
